name: Playwright Tests

on: push

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '16.x'
    - name: Run Playwright tests
      run: |
        npm ci
        npx playwright install
        npx playwright test